# This file created by conda-build 3.28.4
# meta.yaml template originally from:
# C:\b\abs_b04cjq8new\clone\recipe, last modified Thu Feb  1 00:18:30 2024
# ------------------------------------------------

package:
  name: aws-c-mqtt
  version: 0.7.13
source:
  sha256: 04503c704f6d4fba5b0a470a01a96fa2ed702bfa897b0d38071477b0b70ccf82
  url: https://github.com/awslabs/aws-c-mqtt/archive/v0.7.13.tar.gz
build:
  number: '0'
  run_exports:
    - aws-c-mqtt >=0.7.13,<0.7.14.0a0
  string: h2bbff1b_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - cmake 3.26.4 h693b641_0
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - ninja-base 1.10.2 h6d14046_5
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.5 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.5 hd43e919_0
  host:
    - aws-c-cal 0.5.20 h2bbff1b_0
    - aws-c-common 0.8.5 h2bbff1b_0
    - aws-c-compression 0.2.16 h2bbff1b_0
    - aws-c-http 0.6.25 h2bbff1b_0
    - aws-c-io 0.13.10 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - aws-c-common >=0.8.5,<0.8.6.0a0
    - aws-c-http >=0.6.25,<0.6.26.0a0
    - aws-c-io >=0.13.10,<0.13.11.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - if not exist %LIBRARY_INC%\\aws\\mqtt\\mqtt.h exit 1
    - if not exist %PREFIX%\\Library\\bin\\aws-c-mqtt.dll exit 1
about:
  description: 'C99 implementation of the MQTT 3.1.1 and MQTT 5 specifications.

    '
  dev_url: https://github.com/awslabs/aws-c-mqtt
  doc_url: https://github.com/awslabs/aws-c-mqtt
  home: https://github.com/awslabs/aws-c-mqtt
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 implementation of the MQTT
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: b07e6f04-322a-4fc8-83fc-0120217b8b30
  recipe-maintainers:
    - conda-forge/aws-sdk-cpp
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/aws-c-mqtt-feedstock.git
  sha: 57484affe33b904ef4a816d93f39cbafa100050c
